"""Build the independent industry overview and evidence drill-down dashboard.

The dashboard consumes the canonical heatmap and digital-trend JSON outputs.
It does not crawl, classify, cluster, or editorially select records itself.
"""
from pathlib import Path


SITE_DIR = Path(__file__).resolve().parent
OUT_DIR = SITE_DIR / "command-center"
OUT_FILE = OUT_DIR / "index.html"


HTML = r'''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#050b16">
  <meta name="description" content="每日文博资讯的文博行业态势总览与原始证据下钻终端。">
  <title>文博行业数字驾驶舱｜每日文博资讯</title>
  <style>
    :root { --bg:#050a14; --panel:#0b1525; --line:#1d3c57; --line-soft:rgba(133,172,201,.18); --cyan:#57dcff; --blue:#4b8dff; --gold:#ffc857; --mint:#43dfae; --text:#edf7ff; --muted:#9bb3c5; --dim:#6f899c; --danger:#ff8e87; --warn:#ffd177; }
    *{box-sizing:border-box} html,body{margin:0;min-height:100%;background:radial-gradient(circle at 50% -18%,#1a3553 0,#081221 33%,#050a14 72%);color:var(--text);font-family:Inter,"Microsoft YaHei","PingFang SC",sans-serif} body{padding:20px} a{color:inherit} button,select{font:inherit} button{cursor:pointer}.shell{width:min(1720px,100%);margin:auto}
    .topbar{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;padding:9px 2px 18px;border-bottom:1px solid rgba(87,220,255,.32)}.eyebrow{color:var(--cyan);font-size:12px;letter-spacing:.2em}h1{margin:6px 0 0;font-size:clamp(27px,3vw,46px);letter-spacing:.06em;font-weight:750;text-shadow:0 0 18px rgba(87,220,255,.3)}.top-actions{display:flex;align-items:center;gap:10px;color:var(--muted);font-size:13px;text-align:right;flex-wrap:wrap;justify-content:flex-end}.top-actions a,.top-actions button{border:1px solid var(--line);border-radius:5px;background:#0d1b2c;color:var(--text);padding:8px 12px;text-decoration:none}.top-actions a:hover,.top-actions button:hover{border-color:var(--cyan);color:var(--cyan)}.status{white-space:nowrap;font-weight:650}.status.ready{color:var(--mint)}.status.partial,.status.delayed{color:var(--warn)}.status.insufficient{color:#ffb76d}.status.failed{color:var(--danger)}
    .panel{position:relative;overflow:hidden;border:1px solid var(--line);background:linear-gradient(145deg,rgba(16,35,58,.95),rgba(7,15,28,.97));box-shadow:inset 0 0 28px rgba(40,115,165,.08),0 10px 35px rgba(0,0,0,.18);padding:16px}.panel:before{position:absolute;content:"";top:0;left:0;width:64px;height:2px;background:var(--cyan);box-shadow:0 0 12px var(--cyan)}
    .briefing{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.55fr);gap:20px;margin:15px 0 14px;padding:18px}.briefing-kicker,.module-kicker{color:var(--cyan);font-size:11px;letter-spacing:.16em}.briefing h2{margin:7px 0 6px;font-size:clamp(19px,2vw,27px);line-height:1.35}.briefing p{margin:0;color:#b7cad8;font-size:13px;line-height:1.8}.briefing-side{display:grid;align-content:center;gap:11px;padding-left:18px;border-left:1px solid var(--line-soft)}.briefing-side span{color:var(--muted);font-size:12px}.briefing-side strong{display:block;color:var(--text);font-size:16px;margin-top:2px}
    .module{margin-top:16px}.module-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin:0 2px 10px}.module-head h2{margin:3px 0 0;font-size:22px}.module-head p{margin:5px 0 0;color:var(--muted);font-size:13px;line-height:1.65}.module-link{flex:none;border:1px solid var(--line);border-radius:5px;padding:8px 10px;color:var(--cyan);font-size:12px;text-decoration:none}.module-link:hover{border-color:var(--cyan);background:rgba(87,220,255,.08)}
    .local-toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:9px;margin-bottom:12px;padding:11px 12px;border:1px solid var(--line);background:rgba(10,25,42,.7)}.toolbar-label{color:var(--muted);font-size:13px}.segmented{display:flex;gap:3px;padding:3px;border:1px solid var(--line);background:#071321;border-radius:6px}.segmented button{border:0;border-radius:4px;padding:7px 12px;color:var(--muted);background:transparent;font-size:13px}.segmented button.active,.segmented button:hover{color:#03101b;background:var(--cyan)}.filter{min-width:154px;border:1px solid var(--line);border-radius:5px;padding:8px 9px;color:var(--text);background:#0a1727;font-size:13px}.filter:focus{outline:1px solid var(--cyan)}.clear{border:1px solid rgba(255,200,87,.45);border-radius:5px;padding:8px 10px;color:var(--gold);background:transparent;font-size:12px}.clear:hover{background:rgba(255,200,87,.1)}.chips{display:flex;flex-wrap:wrap;gap:6px;margin-left:auto}.chip{display:inline-flex;align-items:center;gap:6px;border:1px solid rgba(87,220,255,.35);border-radius:99px;padding:5px 8px;color:#cfeaf6;background:rgba(27,69,94,.34);font-size:12px}.chip button{border:0;padding:0;color:var(--cyan);background:transparent;font-size:15px;line-height:1}.plain-state{color:var(--dim);font-size:12px;padding:5px 0}
    .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.kpi{position:relative;overflow:hidden;min-height:96px;padding:13px 16px;border:1px solid var(--line);background:linear-gradient(145deg,rgba(16,35,58,.95),rgba(7,15,28,.97))}.kpi:before{position:absolute;content:"";top:0;left:0;width:56px;height:2px;background:var(--cyan)}.kpi-label{color:var(--muted);font-size:12px}.kpi-value{margin-top:8px;font:700 clamp(24px,3vw,37px)/1 "Arial Narrow",Inter,sans-serif;letter-spacing:.03em}.kpi-unit{margin-left:4px;color:var(--cyan);font-size:12px}.kpi-note{margin-top:7px;color:var(--dim);font-size:12px;line-height:1.4}
    .grid-main{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(360px,.75fr);gap:14px}.grid-lower{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(330px,.92fr);gap:14px;margin-top:14px}.panel-title{display:flex;justify-content:space-between;align-items:baseline;gap:10px;margin-bottom:11px;color:#e8f5ff;font-weight:700;letter-spacing:.06em}.panel-title small{color:var(--muted);font-size:12px;font-weight:400;letter-spacing:0}.panel-help{color:var(--dim);font-size:12px;line-height:1.7}#map{height:505px;width:100%}.map-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:5px;color:var(--muted);font-size:12px;line-height:1.55}.map-foot strong{color:var(--gold);font-weight:500}
    .event-list{max-height:505px;overflow:auto;padding-right:4px}.event{padding:11px 0;border-bottom:1px solid var(--line-soft)}.event:last-child{border-bottom:0}.event summary{cursor:pointer;list-style:none}.event summary::-webkit-details-marker{display:none}.event summary:after{content:"＋";float:right;color:var(--cyan);font-size:15px}.event[open] summary:after{content:"－"}.event-title{display:block;color:#f0f8ff;font-size:14px;line-height:1.55;padding-right:18px}.event-meta{display:flex;flex-wrap:wrap;gap:5px 10px;margin-top:7px;color:var(--muted);font-size:12px}.tag{color:var(--gold)}.event-detail{margin:9px 0 0;padding:9px 10px;border-left:2px solid var(--blue);background:rgba(25,61,91,.22);color:#bfd2df;font-size:12px;line-height:1.8}.event-detail a{color:var(--cyan);text-decoration:none}.event-detail a:hover{text-decoration:underline}.evidence-links{display:flex;flex-wrap:wrap;gap:6px 10px;margin-top:6px}.proof{margin-top:8px}.proof summary{color:#d4e7f4;font-size:12px;cursor:pointer}.proof a{display:block;margin-top:5px}.load-more{width:100%;margin-top:10px;border:1px solid var(--line);border-radius:4px;padding:9px;color:var(--cyan);background:rgba(16,42,65,.55);font-size:12px}.load-more:hover{border-color:var(--cyan)}.empty{color:var(--muted);padding:34px 0;text-align:center;font-size:13px}
    .chart{height:350px}.topic-list{display:grid;gap:7px}.topic-row{display:grid;grid-template-columns:minmax(0,1fr) 48px;gap:10px;align-items:center;padding:9px 10px;border:1px solid transparent;border-radius:4px;color:#dcecf7;font-size:13px;background:rgba(8,22,38,.42)}.topic-row:hover,.topic-row.active{border-color:rgba(87,220,255,.5);background:rgba(25,74,103,.35)}.topic-row button{display:block;width:100%;border:0;padding:0;color:inherit;text-align:left;background:none}.topic-row small{display:block;margin-top:3px;color:var(--muted);font-size:11px}.topic-bar{height:6px;margin-top:7px;border-radius:99px;background:#14263a;overflow:hidden}.topic-bar i{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,var(--blue),var(--cyan));box-shadow:0 0 9px rgba(84,215,255,.5)}.topic-count{color:var(--cyan);text-align:right}
    .quality-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:14px;margin-top:14px}.quality-section h3{margin:0 0 8px;font-size:14px;color:#d9edf8}.coverage-grid{display:grid;gap:7px}.coverage-row{display:grid;grid-template-columns:minmax(130px,1fr) auto auto;gap:10px;align-items:center;padding:9px 10px;border-bottom:1px solid var(--line-soft);color:#d8eaf5;font-size:13px}.coverage-row small{color:var(--muted);font-size:11px}.coverage-state{font-size:12px}.coverage-state.complete{color:var(--mint)}.coverage-state.no_update{color:var(--cyan)}.coverage-state.partial{color:var(--warn)}.coverage-state.failed{color:var(--danger)}.quality-facts{display:grid;gap:9px}.quality-fact{padding:10px;border:1px solid var(--line-soft);background:rgba(8,22,38,.4)}.quality-fact span{display:block;color:var(--muted);font-size:11px}.quality-fact strong{display:block;margin-top:3px;font-size:14px}.quality-copy{margin:11px 0 0;color:#b8cad7;font-size:12px;line-height:1.75}.footnote{margin:14px 2px 0;color:var(--muted);font-size:12px;line-height:1.8}.footnote strong{color:#c6d9e8}.error{color:var(--danger);padding:40px;text-align:center}
    @media(max-width:1020px){body{padding:12px}.briefing,.grid-main,.grid-lower,.quality-grid{grid-template-columns:1fr}.kpis{grid-template-columns:repeat(2,1fr)}.briefing-side{padding:12px 0 0;border-left:0;border-top:1px solid var(--line-soft)}#map{height:430px}.chips{width:100%;margin-left:0}.module-head{align-items:flex-start}.event-list{max-height:440px}}
    @media(max-width:600px){.topbar{align-items:flex-start;flex-direction:column}.top-actions{width:100%;justify-content:flex-start;text-align:left}.module-head{flex-direction:column;gap:8px}.module-link{width:100%;text-align:center}.local-toolbar{align-items:flex-start}.filter{flex:1;min-width:130px}.kpi{padding:12px;min-height:84px}.kpi-value{font-size:25px}.panel{padding:12px}.chart{height:285px}.map-foot{align-items:flex-start;flex-direction:column}.coverage-row{grid-template-columns:minmax(0,1fr) auto}.coverage-row small{grid-column:1/-1;order:3}h1{letter-spacing:.03em}}
  </style>
</head>
<body>
<div class="shell">
  <header class="topbar">
    <div><div class="eyebrow">WENBO DAILY · INDUSTRY OVERVIEW</div><h1>文博行业数字驾驶舱</h1></div>
    <div class="top-actions"><span class="status" id="data-status">● 正在核对数据</span><span id="updated">读取数据中</span><a href="../sources.html">方法与信源</a><a href="../heatmap.html">完整行业关注地图</a><a href="../digital-trends.html">完整数字化趋势</a><a href="../index.html">返回每日文博资讯</a><button type="button" id="fullscreen">全屏</button></div>
  </header>
  <section class="panel briefing" aria-label="当前摘要"><div><div class="briefing-kicker">WINDOW BRIEFING · 当前摘要</div><h2 id="briefing-title">正在生成行业摘要</h2><p id="briefing-text">本页只描述已接入的固定权威信源与国家文物局报道样本，不推断全国真实总量。</p></div><div class="briefing-side"><div><span>行业关注数据范围</span><strong id="briefing-industry">—</strong></div><div><span>数字趋势数据范围</span><strong id="briefing-digital">—</strong></div></div></section>
  <main>
    <section class="module" aria-labelledby="industry-title">
      <div class="module-head"><div><div class="module-kicker">MODULE 01 · FIXED-SOURCE MONITORING</div><h2 id="industry-title">行业关注态势</h2><p>观察固定权威信源在不同地区和主题上的相对关注；点击地图省份只筛选本模块事项，不改变全国指数基准。</p></div><a class="module-link" href="../heatmap.html">完整行业关注地图 →</a></div>
      <div class="local-toolbar" aria-label="行业关注筛选"><span class="toolbar-label">观察窗口</span><div class="segmented" id="industry-window"><button data-days="7">近7天</button><button data-days="30" class="active">近30天</button><button data-days="90">近90天</button></div><select id="industry-province" class="filter" aria-label="行业关注地区筛选"><option value="">全部地区</option></select><select id="industry-theme" class="filter" aria-label="行业关注主题筛选"><option value="">全部事件主题</option></select><button type="button" class="clear" id="industry-clear">清除本模块筛选</button><div class="chips" id="industry-chips"></div></div>
      <section class="kpis" aria-label="行业关注指标"><div class="kpi"><div class="kpi-label">独立事项</div><div class="kpi-value" id="i-events">—</div><div class="kpi-note" id="i-events-note">已合并连续报道</div></div><div class="kpi"><div class="kpi-label">涉及地区</div><div class="kpi-value" id="i-provinces">—</div><div class="kpi-note">仅主要发生地进入地图</div></div><div class="kpi"><div class="kpi-label" id="i-leader-label">关注最高地区</div><div class="kpi-value" id="i-leader">—</div><div class="kpi-note" id="i-leader-note">全国归一化指数</div></div><div class="kpi"><div class="kpi-label">窗口数据覆盖</div><div class="kpi-value" id="i-sources">—</div><div class="kpi-note" id="i-sources-note">有效信源 / 固定池 · 完整检查日</div></div></section>
      <div class="grid-main"><section class="panel"><div class="panel-title"><span>全国行业关注分布</span><small id="map-window">固定权威信源 · 近30天</small></div><div id="map"></div><div class="map-foot"><span id="map-scale-note">100 = 当前窗口内样本关注度最高地区；只宜在同一窗口内比较，不等于当地真实活动量。</span><strong id="map-hint">点击省份筛选事项</strong></div></section><section class="panel"><div class="panel-title"><span>重点事项</span><small id="industry-list-summary">—</small></div><div class="event-list" id="industry-list"><div class="empty">正在读取监测记录…</div></div><button class="load-more" id="industry-more" type="button" hidden></button></section></div>
    </section>
    <section class="module" aria-labelledby="digital-title">
      <div class="module-head"><div><div class="module-kicker">MODULE 02 · NCHA ARTICLE SAMPLE</div><h2 id="digital-title">数字化趋势</h2><p>只观察国家文物局“文物新闻”样本中的数字化相关文章；每篇原文 URL 只计一次，方向可多标签。</p></div><a class="module-link" href="../digital-trends.html">完整数字化趋势 →</a></div>
      <div class="local-toolbar" aria-label="数字化趋势筛选"><span class="toolbar-label">观察范围</span><div class="segmented" id="digital-window"><button data-range="90d" class="active">近90天</button><button data-range="12m">近12个月</button><button data-range="3y">近3年</button><button data-range="all">全部</button></div><select id="digital-topic" class="filter" aria-label="数字化方向筛选"><option value="">全部数字化方向</option></select><button type="button" class="clear" id="digital-clear">清除本模块筛选</button><div class="chips" id="digital-chips"></div></div>
      <section class="kpis" aria-label="数字化趋势指标"><div class="kpi"><div class="kpi-label">独立原文</div><div class="kpi-value" id="d-articles">—</div><div class="kpi-note" id="d-articles-note">当前范围按 URL 去重</div></div><div class="kpi"><div class="kpi-label">样本内报道占比</div><div class="kpi-value" id="d-share">—<span class="kpi-unit">%</span></div><div class="kpi-note">同范围国家文物局文物新闻分母</div></div><div class="kpi"><div class="kpi-label">已归类原文</div><div class="kpi-value" id="d-classified">—</div><div class="kpi-note" id="d-classified-note">可多标签，不互斥</div></div><div class="kpi"><div class="kpi-label">未归类独立原文</div><div class="kpi-value" id="d-unclassified">—</div><div class="kpi-note">保留在样本中，不强行归类</div></div></section>
      <div class="grid-lower"><section class="panel"><div class="panel-title"><span>趋势变化</span><small id="trend-note">近90天按周统计</small></div><div id="trend-chart" class="chart"></div><p class="panel-help">短窗口按周、近12个月按月、多年按年。点击趋势点可将对应文章作为可清除的本地筛选。</p></section><section class="panel"><div class="panel-title"><span>数字化行业方向</span><small id="topic-summary">—</small></div><div class="topic-list" id="topics"></div></section></div>
      <section class="panel" style="margin-top:14px"><div class="panel-title"><span>数字化原文明细</span><small id="digital-list-summary">—</small></div><div class="event-list" id="digital-list"><div class="empty">正在读取趋势文章…</div></div><button class="load-more" id="digital-more" type="button" hidden></button></section>
    </section>
    <section class="module" aria-labelledby="quality-title"><div class="module-head"><div><div class="module-kicker">DATA QUALITY · SAMPLE LIMITS</div><h2 id="quality-title">数据质量与适用范围</h2><p>先看覆盖状态，再解释指数和趋势；数据不足时，页面不会把“部分覆盖”写成“正常”。</p></div></div><section class="panel quality-grid"><div class="quality-section"><h3>行业关注 · 固定信源巡检</h3><div class="coverage-grid" id="coverage"><div class="empty">正在核对巡检状态…</div></div><p class="quality-copy" id="industry-quality-copy"></p></div><div class="quality-section"><h3>数字趋势 · 原文与分类</h3><div class="quality-facts" id="digital-quality"></div><p class="quality-copy" id="quality-limits">行业关注≠当地真实文博活动量；数字趋势是国家文物局报道观察≠全国真实数字化项目量。</p></div></section></section>
  </main>
  <p class="footnote"><strong>口径提示：</strong>行业关注直接读取“完整行业关注地图”的固定信源、独立事件和指数权重；数字趋势直接读取“数字化趋势”的国家文物局样本，并将同 URL 的关键词记录合并为一篇文章实体。驾驶舱只做总览与证据下钻，不新增独立采集或评分算法。</p>
</div>
<script src="../lib/wenbo-analysis.js"></script>
<script src="../echarts.min.js"></script>
<script>
  const $ = id => document.getElementById(id);
  const A = window.WenboAnalysis;
  const esc = value => String(value || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const articleUrl = value => value && value.startsWith('/') ? 'https://www.ncha.gov.cn' + value : (value || '#');
  const SHORT_TO_GEO = {'北京':'北京市','天津':'天津市','河北':'河北省','山西':'山西省','内蒙古':'内蒙古自治区','辽宁':'辽宁省','吉林':'吉林省','黑龙江':'黑龙江省','上海':'上海市','江苏':'江苏省','浙江':'浙江省','安徽':'安徽省','福建':'福建省','江西':'江西省','山东':'山东省','河南':'河南省','湖北':'湖北省','湖南':'湖南省','广东':'广东省','广西':'广西壮族自治区','海南':'海南省','重庆':'重庆市','四川':'四川省','贵州':'贵州省','云南':'云南省','西藏':'西藏自治区','陕西':'陕西省','甘肃':'甘肃省','青海':'青海省','宁夏':'宁夏回族自治区','新疆':'新疆维吾尔自治区','台湾':'台湾省','香港':'香港特别行政区','澳门':'澳门特别行政区'};
  const GEO_TO_SHORT = Object.fromEntries(Object.entries(SHORT_TO_GEO).map(([short, full]) => [full, short]));
  let heat, digital, geo, mapChart, trendChart, articles = [];
  let state = {industry:{days:30,province:'',theme:'',visible:10},digital:{range:'90d',topic:'',period:'',visible:10}};
  function readStateFromUrl() { const params=new URLSearchParams(location.search), next={industry:{days:30,province:params.get('province')||'',theme:params.get('theme')||'',visible:10},digital:{range:['90d','12m','3y','all'].includes(params.get('digitalRange'))?params.get('digitalRange'):'90d',topic:params.get('topic')||'',period:params.get('period')||'',visible:10}}; const days=Number(params.get('industryDays')); if([7,30,90].includes(days)) next.industry.days=days; return next; }
  function syncUrl(push) { const params=new URLSearchParams(); if(state.industry.days!==30) params.set('industryDays',state.industry.days); if(state.industry.province) params.set('province',state.industry.province); if(state.industry.theme) params.set('theme',state.industry.theme); if(state.digital.range!=='90d') params.set('digitalRange',state.digital.range); if(state.digital.topic) params.set('topic',state.digital.topic); if(state.digital.period) params.set('period',state.digital.period); const query=params.toString(), target=location.pathname+(query?'?'+query:'')+location.hash, current=location.pathname+location.search+location.hash; if(target!==current) history[push?'pushState':'replaceState'](null,'',target); }
  function syncControls() { document.querySelectorAll('#industry-window button').forEach(button=>button.classList.toggle('active',Number(button.dataset.days)===state.industry.days)); document.querySelectorAll('#digital-window button').forEach(button=>button.classList.toggle('active',button.dataset.range===state.digital.range)); $('industry-province').value=state.industry.province; $('industry-theme').value=state.industry.theme; $('digital-topic').value=state.digital.topic; }

  function rangeLabel(days) { return '近' + days + '天'; }
  function beijingToday() { return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); }
  function freshness(date) { const lag=A.daysBetween(date,beijingToday()); if(lag<=1) return {level:'ready',label:'数据可用'}; if(lag<=3) return {level:'delayed',label:'更新延迟 '+lag+' 天'}; return {level:'failed',label:'数据陈旧 '+lag+' 天'}; }
  function worstFreshness() { const levels={ready:0,delayed:1,failed:2}; const values=[freshness(heat.asOf||heat.generated),freshness(heat.generated),freshness(digital.generated)]; return values.sort((a,b)=>levels[b.level]-levels[a.level])[0]; }
  function isoOffset(asOf, count) { return A.dateKey(A.parseDate(asOf) - (count - 1) * 86400000); }
  function digitalRange() { const end = digital.range.end; if (state.digital.range === '90d') return {label:'近90天', start:isoOffset(end,90), end, gran:'week'}; if (state.digital.range === '12m') return {label:'近12个月', start:isoOffset(end,365), end, gran:'month'}; if (state.digital.range === '3y') return {label:'近3年', start:isoOffset(end,1095), end, gran:'year'}; return {label:'全部历史', start:digital.range.start, end, gran:'year'}; }
  function inside(date, range) { return date >= range.start && date <= range.end; }
  function isoWeekStart(date) { const utc = new Date(A.parseDate(date)); const day = (utc.getUTCDay() + 6) % 7; return A.dateKey(utc.getTime() - day * 86400000); }
  function bucketKey(date, gran) { if (gran === 'week') return isoWeekStart(date); if (gran === 'month') return date.slice(0,7); if (gran === 'year') return date.slice(0,4); return date; }
  function weekKeyStart(key) { const parts=String(key).split('-W'), year=Number(parts[0]), week=Number(parts[1]); if(!year||!week) return ''; const jan4=A.parseDate(year+'-01-04'), day=(new Date(jan4).getUTCDay()+6)%7; return A.dateKey(jan4-day*86400000+(week-1)*7*86400000); }
  function bucketLabel(key, range) { if (range.gran === 'week') return key.slice(5).replace('-', '/') + ' 当周'; if (range.gran === 'month') return key; if (range.gran === 'year') { if (key === range.end.slice(0,4)) return key + '（截至' + range.end.slice(5) + '）'; if (key === range.start.slice(0,4) && range.start.slice(5) !== '01-01') return key + '（' + range.start.slice(5,7) + '月起）'; return key; } return key.slice(5); }
  function allBucketKeys(range) { const keys = new Set(); for (let ms=A.parseDate(range.start); ms<=A.parseDate(range.end); ms+=86400000) keys.add(bucketKey(A.dateKey(ms),range.gran)); return [...keys].sort(); }
  function allDigitalInRange(range) { return articles.filter(article=>inside(article.d,range)); }
  function digitalScope() { const range=digitalRange(), facetRange=allDigitalInRange(range), base=facetRange.filter(article=>!state.digital.topic||article.topics.includes(state.digital.topic)), buckets={}; allBucketKeys(range).forEach(key=>buckets[key]={key,articles:[],source:0}); const sourceGroups=range.gran==='week'?(digital.by_week||[]):range.gran==='month'?(digital.by_month||[]):(digital.by_year||[]); sourceGroups.forEach(row => { const date=range.gran==='week'?weekKeyStart(row.key):range.gran==='month'?row.key+'-01':row.key+'-01-01'; const key=bucketKey(date,range.gran); if (buckets[key]) buckets[key].source += row.source_unique_count || 0; }); base.forEach(article => { const key=bucketKey(article.d,range.gran); if (buckets[key]) buckets[key].articles.push(article); }); const series=Object.values(buckets).sort((a,b)=>a.key.localeCompare(b.key)).map(row => ({...row,count:row.articles.length,share:row.source ? +(row.articles.length/row.source*100).toFixed(2) : 0})); if(state.digital.period&&!buckets[state.digital.period]) state.digital.period=''; const periodArticles=state.digital.period?facetRange.filter(article=>bucketKey(article.d,range.gran)===state.digital.period):facetRange; const shown=state.digital.topic?periodArticles.filter(article=>article.topics.includes(state.digital.topic)):periodArticles; return {range,facetArticles:periodArticles,base,shown,series}; }
  function industryScope() { const panelEvents=(heat.events||[]).concat(heat.nationalEvents||[]); const matching=panelEvents.filter(event => A.eventInRange(event,heat.asOf,state.industry.days,false) && (!state.industry.theme || (event.themes||[]).includes(state.industry.theme)) && (!state.industry.province || event.primaryProvince===state.industry.province)); const allRows=A.provinceRows(heat.events||[],{asOf:heat.asOf,decay:heat.decay,days:state.industry.days,theme:state.industry.theme}); const selectedRow=state.industry.province ? allRows.find(row=>row.name===state.industry.province) : null; const coverage=A.coverageForWindow(heat.coverage,heat.asOf,state.industry.days,false); matching.sort((a,b)=>A.eventScore(b,heat.asOf,heat.decay)-A.eventScore(a,heat.asOf,heat.decay)); return {events:matching,allRows,selectedRow,coverage}; }
  function sourceStateText(stateName) { return ({complete:'完整',no_update:'无更新',partial:'部分覆盖',failed:'失败'})[stateName] || '待核对'; }
  function coverageStateText(stateName) { return ({ready:'数据可用',partial:'部分覆盖',insufficient:'覆盖不足',failed:'数据异常'})[stateName] || '正在核对'; }
  function sourceLinks(sources) { return (sources||[]).map(source => '<a href="'+esc(source.url)+'" target="_blank" rel="noopener">'+esc(source.name)+'</a>').join(''); }
  function eventMarkup(event) { const score=A.eventScore(event,heat.asOf,heat.decay), age=A.daysBetween(event.lastDate,heat.asOf), reason=esc((event.impactLabel||'关注')+'级事项 · '+(event.sourceCount||0)+'个固定来源印证 · '+age+'日内更新'), reports=(event.reports||[]).map(report => '<a href="'+esc(report.url)+'" target="_blank" rel="noopener">'+esc(report.date)+'｜'+esc(report.title)+'</a>').join(''); return '<details class="event"><summary><span class="event-title">'+esc(event.title)+'</span><div class="event-meta"><span>'+esc(event.lastDate)+'</span><span class="tag">'+esc(event.primaryProvince||'全国性')+'</span><span>'+esc(event.primaryTheme||(event.themes||[])[0]||'行业动态')+'</span><span>指数 '+score.toFixed(0)+'</span></div></summary><div class="event-detail"><strong>结构化依据：</strong>'+reason+'<br>地点明确度 '+Math.round((event.locationConfidence||0)*100)+'% · 已合并 '+(event.reportCount||1)+' 条相关报道<div class="evidence-links">'+sourceLinks(event.sources)+'</div>'+(reports?'<details class="proof"><summary>查看全部 '+(event.reports||[]).length+' 条原始报道</summary>'+reports+'</details>':'')+'</div></details>'; }
  function articleMarkup(article) { const topics=article.topics.length ? article.topics.join('、') : '未归类', keywords=article.matchedKeywords.length ? article.matchedKeywords.join('、') : '—', merged=article.matched_titles.length ? '<details class="proof"><summary>查看合并命中片段 '+article.matched_titles.length+' 条</summary>'+article.matched_titles.map(title=>'<div>'+esc(title)+'</div>').join('')+'</details>' : '', digest=article.digest_snippets.length ? '<details class="proof"><summary>查看摘编命中片段 '+article.digest_snippets.length+' 条</summary>'+article.digest_snippets.map(title=>'<div>'+esc(title)+'</div>').join('')+'</details>' : ''; return '<details class="event"><summary><span class="event-title">'+esc(article.t)+'</span><div class="event-meta"><span>'+esc(article.d)+'</span><span class="tag">'+esc(topics)+'</span><span>命中词：'+esc(keywords)+'</span></div></summary><div class="event-detail">按原文 URL 聚合 '+article.recordCount+' 条命中记录；方向：'+esc(topics)+'<br><a href="'+esc(articleUrl(article.u))+'" target="_blank" rel="noopener">打开国家文物局原文 →</a>'+merged+digest+'</div></details>'; }
  function renderChips(target, entries, clear) { const box=$(target); box.innerHTML=entries.length ? entries.map(entry=>'<span class="chip">'+esc(entry.label)+'<button type="button" data-clear="'+esc(entry.key)+'" aria-label="清除 '+esc(entry.label)+'">×</button></span>').join('') : '<span class="plain-state">当前：全部样本</span>'; box.querySelectorAll('[data-clear]').forEach(button=>button.addEventListener('click',()=>clear(button.dataset.clear))); }
  function renderIndustry(scope) { const {events,allRows,selectedRow,coverage}=scope, hasProvince=Boolean(state.industry.province); $('i-events').textContent=events.length; $('i-events-note').textContent=hasProvince?'当前地区筛选后的事项数':'已合并连续报道'; $('i-provinces').textContent=hasProvince?(selectedRow?1:0):allRows.length; $('i-leader-label').textContent=hasProvince?'当前筛选地区':'关注最高地区'; $('i-leader').textContent=hasProvince?(selectedRow?selectedRow.name:'—'):(allRows[0]?allRows[0].name:'—'); $('i-leader-note').textContent=hasProvince?(selectedRow?'全国窗口/主题基准中的归一化指数 '+selectedRow.index.toFixed(0):'当前窗口/主题无事件，不回退全国最高地区'):(allRows[0]?'全国归一化指数 '+allRows[0].index.toFixed(0):'暂无地域事件'); $('i-sources').innerHTML=(coverage.rate*100).toFixed(1)+'<span class="kpi-unit">%</span>'; $('i-sources-note').textContent='有效信源 '+coverage.effectiveSources+'/'+coverage.panel.length+' · 完整检查日 '+coverage.completeDays+'/'+state.industry.days+' · '+coverageStateText(coverage.state); $('map-window').textContent='固定权威信源 · '+rangeLabel(state.industry.days)+' · '+coverage.start+'—'+coverage.end; $('map-scale-note').textContent=state.industry.theme?'100 = 当前窗口 + 当前事件主题样本中的最高地区；不建议跨主题直接比较。':'100 = 当前窗口样本关注度最高地区；不建议跨窗口直接比较。'; renderChips('industry-chips',[state.industry.province&&{key:'province',label:'地区：'+state.industry.province},state.industry.theme&&{key:'theme',label:'主题：'+state.industry.theme}].filter(Boolean),key=>{state.industry[key]=''; if(key==='province') $('industry-province').value=''; if(key==='theme') $('industry-theme').value=''; state.industry.visible=10; renderAll();}); const shown=events.slice(0,state.industry.visible); $('industry-list').innerHTML=shown.length?shown.map(eventMarkup).join(''):'<div class="empty">当前本模块筛选下暂无合格事项。可扩大窗口或清除地区、主题筛选。</div>'; $('industry-list-summary').textContent='已显示 '+shown.length+' / 共 '+events.length+' 项'; const more=$('industry-more'); more.hidden=shown.length>=events.length; more.textContent='加载更多事项（已显示 '+shown.length+' / '+events.length+'）'; renderMap(allRows); $('map-hint').textContent=hasProvince?'已筛选 '+state.industry.province+' · 再点该省恢复全国':'点击省份筛选右侧事项'; }
  function renderMap(rows) { if (!window.echarts || !geo) { $('map').innerHTML='<div class="error">地图组件不可用，请打开完整行业关注地图查看。</div>'; return; } if(mapChart) mapChart.dispose(); mapChart=echarts.init($('map')); const data=rows.map(row=>({name:SHORT_TO_GEO[row.name]||row.name,value:+row.index.toFixed(1),selected:state.industry.province===row.name})); mapChart.setOption({tooltip:{trigger:'item',backgroundColor:'#0b1525',borderColor:'#2a6484',textStyle:{color:'#eaf5ff'},formatter:params=>{const row=rows.find(item=>(SHORT_TO_GEO[item.name]||item.name)===params.name); return row?'<b>'+row.name+'</b><br>关注指数：'+row.index.toFixed(0)+'<br>窗口事项：'+row.eventCount+'<br>100 = 本窗口最高地区':'<b>'+params.name+'</b><br>当前窗口暂无地域事项';}},visualMap:{min:0,max:100,left:12,bottom:4,text:['高','低'],textStyle:{color:'#a4bdcf'},inRange:{color:['#102238','#155174','#2f9fc8','#8bdcff']},calculable:false},series:[{type:'map',map:'wenbo-china',roam:true,zoom:1.08,selectedMode:'single',data,label:{show:false},itemStyle:{areaColor:'#0d1c2d',borderColor:'#315872',borderWidth:1},select:{itemStyle:{areaColor:'#a9efff'}},emphasis:{label:{show:true,color:'#fff'},itemStyle:{areaColor:'#38bce9'}}}]}); mapChart.on('click',params=>{const name=GEO_TO_SHORT[params.name]||params.name; if(!rows.some(row=>row.name===name)) return; state.industry.province=state.industry.province===name?'':name; $('industry-province').value=state.industry.province; state.industry.visible=10; renderAll();}); }
  function renderTopics(scope) { const counts={}; scope.facetArticles.forEach(article=>(article.topics||[]).forEach(topic=>counts[topic]=(counts[topic]||0)+1)); const info=digital.topic_info||[], max=Math.max(1,...info.map(item=>counts[item.name]||0)); $('topics').innerHTML=info.map(item=>'<div class="topic-row '+(state.digital.topic===item.name?'active':'')+'"><button type="button" data-topic="'+esc(item.name)+'"><strong>'+esc(item.name)+'</strong><small>'+esc(item.description)+'</small><div class="topic-bar"><i style="width:'+Math.round((counts[item.name]||0)/max*100)+'%"></i></div></button><div class="topic-count">'+(counts[item.name]||0)+'</div></div>').join(''); $('topic-summary').textContent='当前'+(state.digital.period?'趋势点':'范围')+' '+scope.facetArticles.length+' 篇独立原文 · 方向统计不受已选方向影响 · 可多标签'; $('topics').querySelectorAll('[data-topic]').forEach(button=>button.addEventListener('click',()=>{state.digital.topic=state.digital.topic===button.dataset.topic?'':button.dataset.topic; $('digital-topic').value=state.digital.topic; state.digital.period=''; state.digital.visible=10; renderAll(true);})); }
  function renderTrend(scope) { if(!window.echarts) return; if(trendChart) trendChart.dispose(); trendChart=echarts.init($('trend-chart')); const labels=scope.series.map(row=>bucketLabel(row.key,scope.range)), counts=scope.series.map(row=>row.count), shares=scope.series.map(row=>row.share); trendChart.setOption({grid:{left:48,right:52,top:34,bottom:48},tooltip:{trigger:'axis',backgroundColor:'#0b1525',borderColor:'#2a6484',textStyle:{color:'#eaf5ff'},formatter:params=>{const row=scope.series[params[0].dataIndex];return labels[params[0].dataIndex]+'<br>独立原文：<b>'+row.count+'</b><br>占样本内文物新闻：<b>'+row.share+'%</b>'; }},legend:{top:0,textStyle:{color:'#b3c8d8'},data:['独立原文数','占样本内文物新闻']},xAxis:{type:'category',data:labels,axisLabel:{color:'#9ab5c7',interval:scope.range.gran==='week'?1:0},axisLine:{lineStyle:{color:'#29475d'}}},yAxis:[{type:'value',name:'篇',minInterval:1,nameTextStyle:{color:'#9ab5c7'},axisLabel:{color:'#9ab5c7'},splitLine:{lineStyle:{color:'rgba(134,160,183,.12)'}}},{type:'value',name:'%',min:0,axisLabel:{color:'#9ab5c7'},splitLine:{show:false}}],series:[{name:'独立原文数',type:'line',smooth:scope.range.gran!=='week',symbol:'circle',symbolSize:7,data:counts,lineStyle:{width:3,color:'#54d7ff'},itemStyle:{color:'#54d7ff'},areaStyle:{color:'rgba(84,215,255,.1)'}},{name:'占样本内文物新闻',type:'line',smooth:scope.range.gran!=='week',yAxisIndex:1,symbol:'circle',symbolSize:6,data:shares,lineStyle:{width:2,color:'#ffc857'},itemStyle:{color:'#ffc857'}}]}); trendChart.on('click',params=>{const row=scope.series[params.dataIndex]; if(!row) return; state.digital.period=state.digital.period===row.key?'':row.key; state.digital.visible=10; renderAll();}); $('trend-note').textContent=scope.range.label+' · '+({week:'按周',month:'按月',year:'按年'})[scope.range.gran]+' · 图表与明细同口径'; }
  function renderDigital(scope) { const currentRows=state.digital.period?scope.series.filter(row=>row.key===state.digital.period):scope.series, currentSource=currentRows.reduce((sum,row)=>sum+row.source,0), classified=scope.shown.filter(article=>article.topics.length).length, unclassified=scope.shown.length-classified; $('d-articles').textContent=scope.shown.length; $('d-articles-note').textContent=state.digital.period?'当前趋势点筛选后的独立 URL':'当前范围按 URL 去重'; $('d-share').firstChild.textContent=currentSource ? (scope.shown.length/currentSource*100).toFixed(2) : '—'; $('d-classified').textContent=classified; $('d-classified-note').textContent=classified+'/'+scope.shown.length+' 篇当前最终样本'; $('d-unclassified').textContent=unclassified; renderChips('digital-chips',[state.digital.topic&&{key:'topic',label:'方向：'+state.digital.topic},state.digital.period&&{key:'period',label:'趋势点：'+bucketLabel(state.digital.period,scope.range)}].filter(Boolean),key=>{state.digital[key]=''; if(key==='topic') $('digital-topic').value=''; state.digital.visible=10; renderAll(true);}); renderTopics(scope); renderTrend(scope); const shown=scope.shown.slice(0,state.digital.visible); $('digital-list').innerHTML=shown.length?shown.map(articleMarkup).join(''):'<div class="empty">当前本模块筛选下暂无数字化原文。</div>'; $('digital-list-summary').textContent='已显示 '+shown.length+' / 共 '+scope.shown.length+' 篇独立原文'; const more=$('digital-more'); more.hidden=shown.length>=scope.shown.length; more.textContent='加载更多原文（已显示 '+shown.length+' / '+scope.shown.length+'）'; }
  function renderQuality(industry, dScope) { const c=industry.coverage; $('coverage').innerHTML=c.rows.map(row=>'<div class="coverage-row"><span>'+esc(row.name)+'</span><small>'+esc(row.actualStart||'—')+'—'+esc(row.actualEnd||'—')+' · '+row.good+'/'+state.industry.days+' 天有效</small><span class="coverage-state '+row.state+'">'+sourceStateText(row.state)+'</span></div>').join(''); const stats=heat.stats||{}, total=stats.totalMonitoredRecords||0, assigned=Math.max(0,total-(stats.unassigned||0)), assignedRate=total?(assigned/total*100).toFixed(1):'0.0', legacy=stats.legacyBaselineRecords||0, operational=stats.operationalRecords||0, monitoringStart=(heat.coverage&&heat.coverage.monitoringStart)||heat.start||'—'; $('industry-quality-copy').textContent='本窗口 '+c.start+'—'+c.end+'：'+c.successful+'/'+c.planned+' 次有效检查（'+(c.rate*100).toFixed(1)+'%），完整检查日 '+c.completeDays+'/'+state.industry.days+'。监测原始范围 '+monitoringStart+'—'+heat.asOf+'；地域可归属记录 '+assigned+'/'+total+'（'+assignedRate+'%），未归属 '+(stats.unassigned||0)+' 条，其中仅主要发生地明确的 '+(stats.includedProvincialRecords||0)+' 条进入地区地图。历史回溯基线 '+legacy+' 条 / 正式运行监测 '+operational+' 条；固定信源日常巡检从 '+monitoringStart+' 开始累积，回溯期的 partial 记录不代表系统已连续运行。'; const allArticles=articles.length, classified=articles.filter(article=>article.topics.length).length, unclassified=allArticles-classified; $('digital-quality').innerHTML='<div class="quality-fact"><span>数字趋势更新时间与范围</span><strong>'+esc(digital.generated)+' · '+esc(digital.range.start)+'—'+esc(digital.range.end)+'</strong></div><div class="quality-fact"><span>数字化分类覆盖率</span><strong>'+classified+'/'+allArticles+' 篇（'+(allArticles?(classified/allArticles*100).toFixed(1):'0.0')+'%）</strong></div><div class="quality-fact"><span>未归类独立原文</span><strong>'+unclassified+' 篇 · 保留原始证据，不强行贴标签</strong></div><div class="quality-fact"><span>当前观察范围</span><strong>'+dScope.range.label+' · '+dScope.range.start+'—'+dScope.range.end+'</strong></div>'; }
  function renderBriefing(industry, dScope) { const top=industry.events[0], leader=industry.selectedRow||(!state.industry.province?industry.allRows[0]:null); $('briefing-title').textContent=top?'近'+state.industry.days+'天重点行业信号：'+top.title:'当前行业筛选下暂无合格事项'; const leadText=state.industry.province?(industry.selectedRow?'当前筛选地区：'+industry.selectedRow.name+'（全国基准指数 '+industry.selectedRow.index.toFixed(0)+'）':'当前筛选地区无事件'):(leader?'当前关注最高地区：'+leader.name+'（指数 '+leader.index.toFixed(0)+'）':'当前无地域事件'); const topicCounts={}; dScope.facetArticles.forEach(article=>(article.topics||[]).forEach(topic=>topicCounts[topic]=(topicCounts[topic]||0)+1)); const mainTopic=Object.keys(topicCounts).sort((a,b)=>topicCounts[b]-topicCounts[a])[0]; $('briefing-text').textContent=leadText+'；当前数字范围主导方向：'+(mainTopic?mainTopic+'（'+topicCounts[mainTopic]+' 篇独立原文）':'暂无已归类方向')+'。以上均为本页接入样本内信号，不代表全国真实行业总量。'; $('briefing-industry').textContent='更新 '+heat.generated+' · '+coverageStateText(industry.coverage.state); $('briefing-digital').textContent='更新 '+digital.generated+' · '+dScope.range.label+' · '+dScope.range.start+'—'+dScope.range.end; }
  function renderStatus(industry) { const trendUsable=Boolean(digital && articles.length && !(digital.quality&&digital.quality.source_fetch_complete===false)); const fresh=worstFreshness(), industryFresh=freshness(heat.asOf||heat.generated), digitalFresh=freshness(digital.generated); let stateName='ready', text='数据可用'; if(industry.coverage.state==='failed'||!trendUsable||fresh.level==='failed'){stateName='failed';text=fresh.level==='failed'?'数据陈旧/异常':'数据异常';}else if(fresh.level==='delayed'){stateName='delayed';text='更新延迟';}else if(industry.coverage.state==='insufficient'){stateName='insufficient';text='覆盖不足';}else if(industry.coverage.state==='partial'){stateName='partial';text='数据部分覆盖';} const el=$('data-status'); el.className='status '+stateName; el.textContent='● '+text; $('updated').textContent='行业关注 '+heat.generated+'（'+industryFresh.label+'） · 数字趋势 '+digital.generated+'（'+digitalFresh.label+'）'; }
  function renderAll(pushUrl) { const industry=industryScope(), dScope=digitalScope(); syncControls(); syncUrl(Boolean(pushUrl)); renderStatus(industry); renderBriefing(industry,dScope); renderIndustry(industry); renderDigital(dScope); renderQuality(industry,dScope); }
  function fillFilters() { const provinces=[...new Set((heat.events||[]).map(event=>event.primaryProvince).filter(Boolean))].sort(); $('industry-province').innerHTML='<option value="">全部地区</option>'+provinces.map(name=>'<option value="'+esc(name)+'">'+esc(name)+'</option>').join(''); const themes=[...new Set((heat.events||[]).flatMap(event=>event.themes||[]))].sort(); $('industry-theme').innerHTML='<option value="">全部事件主题</option>'+themes.map(name=>'<option value="'+esc(name)+'">'+esc(name)+'</option>').join(''); const topics=digital.topic_info||[]; $('digital-topic').innerHTML='<option value="">全部数字化方向</option>'+topics.map(item=>'<option value="'+esc(item.name)+'">'+esc(item.name)+'</option>').join(''); if(!provinces.includes(state.industry.province)) state.industry.province=''; if(!themes.includes(state.industry.theme)) state.industry.theme=''; if(!topics.some(item=>item.name===state.digital.topic)) state.digital.topic=''; }
  async function init() { try { const [heatResponse,digitalResponse,geoResponse]=await Promise.all([fetch('../heatmap-data.json'),fetch('../digital-data.json'),fetch('../lib/china.json')]); if(!heatResponse.ok||!digitalResponse.ok||!geoResponse.ok) throw new Error('数据文件不可用'); heat=await heatResponse.json(); digital=await digitalResponse.json(); geo=await geoResponse.json(); articles=(digital.articles&&digital.articles.length?digital.articles:A.aggregateArticles(digital.items||[])).map(article=>({u:article.u||'',t:article.t||'',d:article.d||'',l:article.l||'',topics:article.topics||[],matchedKeywords:article.matched_keywords||article.matchedKeywords||[],digest_snippets:article.digest_snippets||[],matched_titles:article.matched_titles||article.excerpts||[],recordCount:article.record_count||article.recordCount||1})); const features=(geo.features||[]).filter(feature=>feature.properties&&feature.properties.name); echarts.registerMap('wenbo-china',{...geo,features}); fillFilters(); renderAll(); window.addEventListener('resize',()=>{if(mapChart)mapChart.resize();if(trendChart)trendChart.resize();}); } catch(error) { console.error(error); $('data-status').className='status failed'; $('data-status').textContent='● 数据异常'; document.querySelector('main').innerHTML='<div class="panel error">驾驶舱数据加载失败，请返回每日文博资讯或稍后重试。</div>'; } }
  document.querySelectorAll('#industry-window button').forEach(button=>button.addEventListener('click',()=>{state.industry.days=Number(button.dataset.days);state.industry.visible=10;document.querySelectorAll('#industry-window button').forEach(item=>item.classList.toggle('active',item===button));renderAll(true);})); $('industry-province').addEventListener('change',event=>{state.industry.province=event.target.value;state.industry.visible=10;renderAll(true);}); $('industry-theme').addEventListener('change',event=>{state.industry.theme=event.target.value;state.industry.visible=10;renderAll(true);}); $('industry-clear').addEventListener('click',()=>{state.industry.province='';state.industry.theme='';state.industry.visible=10;$('industry-province').value='';$('industry-theme').value='';renderAll(true);}); $('industry-more').addEventListener('click',()=>{state.industry.visible+=10;renderAll(false);});
  document.querySelectorAll('#digital-window button').forEach(button=>button.addEventListener('click',()=>{state.digital.range=button.dataset.range;state.digital.period='';state.digital.visible=10;document.querySelectorAll('#digital-window button').forEach(item=>item.classList.toggle('active',item===button));renderAll(true);})); $('digital-topic').addEventListener('change',event=>{state.digital.topic=event.target.value;state.digital.period='';state.digital.visible=10;renderAll(true);}); $('digital-clear').addEventListener('click',()=>{state.digital.topic='';state.digital.period='';state.digital.visible=10;$('digital-topic').value='';renderAll(true);}); $('digital-more').addEventListener('click',()=>{state.digital.visible+=10;renderAll(false);}); $('fullscreen').addEventListener('click',()=>document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen()); state=readStateFromUrl(); window.addEventListener('popstate',()=>{state=readStateFromUrl();renderAll(false);}); init();
</script>
</body>
</html>'''


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(HTML, encoding="utf-8")
    print(f"Command center: {OUT_FILE}")


if __name__ == "__main__":
    main()
